AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-lambda-mq-integration-app

  Sample SAM Template for sam-lambda-mq-integration-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Parameters:
  brokerARNParameter:
    Type: String
    #Default: arn:aws:mq:us-west-2:986112483391:broker:Broker:b-a7489285-df24-4dc8-b304-f4a2444fdec9
    Default: arn:aws:mq:us-west-2:123456789:broker:Broker:b-222222-1111-1111-1111-111111111112
  # mqdemoPassword:
  #   Type: String
  #   Default: notAGoodPassword

Resources:
  MQQueueAccessSecret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: SecretForMQQueueAccess
      Description: "Secret for accessing a queue on the ActiveMQ broker."
      SecretString: '{"username":"lambdaIntegrationUser","password":"lambdaIntegrationUser"}'

  MQSubscriberFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: MQSubscriberFunction
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.6
      Policies:
        - Statement:
          - Effect: Allow
            Resource: '*'
            Action:
            - mq:DescribeBroker
            - secretsmanager:GetSecretValue
            - ec2:CreateNetworkInterface
            - ec2:DescribeNetworkInterfaces
            - ec2:DescribeVpcs
            - ec2:DeleteNetworkInterface
            - ec2:DescribeSubnets
            - ec2:DescribeSecurityGroups
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
      Events:
        MQEvent:
          Type: MQ
          Properties:
            Broker: !Ref brokerARNParameter
            Queues:
              - "samQueue"
            SourceAccessConfigurations:
              - Type: BASIC_AUTH
                URI: !Ref MQQueueAccessSecret

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  MQSubscriberFunction:
    Description: "MQ Subscriber Lambda Function ARN"
    Value: !GetAtt MQSubscriberFunction.Arn
  MQSubscriberFunctionIamRole:
    Description: "Implicit IAM Role created for MQSubscriber function"
    Value: !GetAtt MQSubscriberFunctionRole.Arn

